### ISSUE TITLE
Permission Issue When Pushing to Repository

### ISSUE THREAD

**Issue by headrickleonard** [javaScriptKampala/z-js#3]
I am encountering a permission issue when attempting to push to the repository `javaScriptKampala/z-js.git`. This issue prevents me from pushing changes to the remote repository.

### steps to reproduce
1.Attempt to push changes to the repository using the command

```bash
git push origin feature/utility-functions
```
2.Observe the following error message:

`remote: Permission to javaScriptKampala/z-js.git denied to headrickleonard.
fatal: unable to access 'https://github.com/javaScriptKampala/z-js.git/': The requested URL returned error: 403
`

**Comment by Hussseinkizz** [comment]
Thanks for the initiative and please retry, since there's a pending pr I assume someone else was able to push successfully or so, otherwise retry and let me know!

**Comment by headrickleonard** [comment]
`git push origin feature/utility-functions`

* remote: `Permission to javaScriptKampala/z-js.git` denied to` headrickleonard.`
* fatal: unable to access `'https://github.com/javaScriptKampala/z-js.git/':` The requested URL returned error: `403`

i still get that

**Comment by Hussseinkizz** [comment]
Try forking instead and contribute in then make a pr from there!

**Comment by Hussseinkizz** [comment]
hey how far with this?
